my_diary/urls.py
from django.contrib import admin
#to verify
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_diary1.urls')),
    path('users/', include('users.urls')),
    
    ]

my_diary1/urls.py
'''Defines urls for my_diary1.'''
from django.urls import path

from . import views

#namespace below
app_name = 'my_diary1'

urlpatterns = [
    #homepage

    path('', views.homepage, name = 'homepage'),
    path('days/', views.days, name = 'days'),
    path('days/int<day_id>/', views.day, name = 'day'),
    path('new_day/', views.new_day, name= 'new_day'),
    path('new_thought/int<day_id>/', views.new_thought, name = 'new_thought'),
    path('edit_thought/int<thought_id>/', views.edit_thought, name ='edit_thought'),
    #path('thoughts/',views.thoughts , name = 'thoughts'),

]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name= 'login'),
    path('logout/', views.logout_view, name= 'logout'),
    path('register/', views.register, name= 'register'),
    
]

my_diary1/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Day(models.Model):
    '''The day when a user is writing their thoughts'''
    day_name = models.CharField(max_length = 10)
    date = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User,  on_delete=models.CASCADE)

    def __str__(self):
        return self.day_name
    
#define the thoughts model
class Thought(models.Model):
    '''Thoughts you want to let out about that particular day'''
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    # ForeignKey should specify the on_delete behavior, here set to CASCADE
    #foreignkey is used to refer to another record in the database
    #connects the thoughs oa a user to the specific day
    text = models.TextField()
    date = models.DateTimeField(auto_now_add = True)

    #more information on managing the model you can adda meta class

    def __str__(self):#the __str__ method tells django what to show when a thought is called
        #return the first 30 words
        if len(self.text) > 30:
            return self.text[:30] + '...'
        else:
            return self.text
        

users/models.py
from django.db import models

# Create your models here.

my_diary1/forms.py
from django import forms

from .models import Day

from .models import Thought

class DayForm(forms.ModelForm):
    class Meta:
        model = Day
        fields = ['day_name']
        labels = {'day_name': ''}

class ThoughtForm(forms.ModelForm):
    class Meta:
        model = Thought
        fields = ['text']
        labels = {'text': ''}
    

my_diary1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Day,Thought
from .forms import DayForm,ThoughtForm


# Create your views here.
def homepage(request):
    '''this gives value of the homepage'''
    return render(request, 'my_diary1/homepage.html')

@login_required
def days(request):
    days = Day.objects.filter(owner=request.user).order_by('date')
    context = {'days': days}
    return render(request, 'my_diary1/days.html', context)

@login_required
def day(request,day_id):
    day = Day.objects.get(id=day_id)
    if day.owner != request.user:
        raise Http404
    thoughts = day.thought_set.order_by('date')
    context = {'day': day, 'thoughts': thoughts}
    return render(request, 'my_diary1/day.html', context)

#adding new day
@login_required
def new_day(request):
    if request.method != 'POST':
        form = DayForm()
    else:
        form = DayForm(request.POST)
        if form.is_valid():
            new_day = form.save(commit=False)
            new_day.owner = request.user
            new_day.save()
            
            return HttpResponseRedirect(reverse('my_diary1:days'))
        
    context = {'form': form}
    return render (request, 'my_diary1/new_day.html', context )

@login_required
def new_thought(request,day_id):
    day = Day.objects.get(id=day_id)

    if request.method != 'POST':
        form = ThoughtForm()
    else:
        form = ThoughtForm(data=request.POST)
        if form.is_valid():
            new_thought = form.save(commit=False)
            new_thought.day = day
            new_thought.save()
            return HttpResponseRedirect(reverse('my_diary1:day', args=[day_id]))
        
    context = {'day': day, 'form': form}
    return render(request, 'my_diary1/new_thought.html', context)

@login_required
def edit_thought(request,thought_id):
    thought = Thought.objects.get(id=thought_id)
    day = thought.day
    if day.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = ThoughtForm(instance=thought)
    else:
        form = ThoughtForm(instance=thought,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('my_diary1:day', args=[day.id]))
        
    context ={'thought': thought, 'day': day, 'form': form}
    return render(request, 'my_diary1/edit_thought.html', context)

users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('my_diary1:homepage'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('my_diary1:homepage'))
        
    context = {'form': form}
    return render(request, 'users/register.html', context)

my_diary1/templates/my_diary1/base.html
<p>
    <a href="{%url 'my_diary1:homepage' %}">My Diary - </a>
    <a href="{% url 'my_diary1:days' %}">Days</a> - 
    {% if user.is_authenticated %}
    <p>Hello, {{ user.username }}.
     <a href="{% url 'users:logout' %}">Log out</a></p>
    
    {% else %}
    <a href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:login' %}">Log in</a>
    {% endif %} 

</p>

{% block content %} {% endblock content %}

my_diary1/templates/my_diary1/day.html
{% extends 'my_diary1/base.html' %}

{% block content %}

<p>Day :  {{day}}</p>
<p>Thoughts:</p>

<ul>
    {% for thought in thoughts%}
    <li>
        <p>{{thought.date|date:'M d, Y H:i'}}</p>
        <p>{{thought.text|linebreaks}}</p>
        <p>
            <a href="{% url 'my_diary1:edit_thought' thought.id %}">edit thought</a>
        </p>
    </li>
    {% empty %}
    <li>No thoughts on this particular day!?</li>
    {% endfor %}
</ul>
<p>
<a href="{%url 'my_diary1:new_thought' day.id %}">Add new thought</a>
</p>
{% endblock content %}

my_diary1/templates/my_diary1/days.html
{% extends 'my_diary1/base.html' %}

{% block content %}
<p>Days</p>
<ul>
    {% for day in days %}
    <li>
        <a href="{% url 'my_diary1:day' day.id %}">{{day}}</a>
        </li>
    {% empty %}
    <li>No days have been added yet.</li>
    {% endfor %}

</ul>

<a href="{% url 'my_diary1:new_day' %}">Add a new day</a>


{% endblock content %}

my_diary1/templates/my_diary1/edit_thought.html
{% extends 'my_diary1/base.html'%}

{% block content %}

<p><a href="{% url 'my_diary1:day' day.id %}">{{day}}</a></p>
<p>Edit your thoughts</p>
<form action="{% url 'my_diary1:edit_thought' thought.id %}" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

my_diary1/templates/my_diary1/homepage.html
{% extends 'my_diary1/base.html'%}

{% block content %}
<p> Hey you!This is supposed to be private.</p>

{% endblock content %}

my_diary1/templates/my_diary1/new_day.html
{% extends 'my_diary1/base.html'%}

{% block content %}

<p>So When is Today?</p>

<form action="{% url 'my_diary1:new_day'%}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">add day</button>
</form>

{% endblock content%}

my_diary1/templates/my_diary1/new_thought.html
{% extends 'my_diary1/base.html' %}

{% block content %}
<p><a href="{% url 'my_diary1:day' day.id %}">{{day}}</a></p>

<p>Put it down here bestie:</p>
<form action="{% url 'my_diary1:new_thought' day.id %}" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button name="submit">Add Thought</button>
</form>

{% endblock content %}

users/templates/users/login.html
{% extends 'my_diary1/base.html' %}

{% block content %}
  {% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}">
    {%csrf_token%}
    {{form.as_p}}
    <button name="submit">Log in</button>

    <input type="hidden" name="next" value="{% url 'my_diary1:homepage' %}"/>
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends 'my_diary1/base.html '%}

{% block content %}
<form method="post" action="{% url 'users:register' %}"> 
    {%csrf_token%}
    {{form.as_p}}
    <button name="submit">Register</button>
    <input type="hidden" name="next" value="{% url 'my_diary1:homepage' %}"/>
</form>
{% endblock content %}